const data: Object = {
  cryptocurrency: [
    {
      name: 'MyCryptoCheckout',
      category: 'Payments',
      goal: '$240,000',
      interest: 'Sponsored',
      dateActive: '3d left',
      column: 'none',
      date: '2021-08-17T23:35:00',
      important:
        'MyCryptoCheckout will hold a Genesis event on the 14. Aug. The Genesis will happen on CoinList.',
      ticker: 'RWD',
      tokenType: 'ERC20',
      tokenPrice: '1 RWD = 0.012 USD',
      fundraisingGoal: '75,000,000 TOKEN',
      totalTokens: '500,000,000',
      tokenSale: '50%',
      roleOfToken: 'UTILITY',
      links: [
        {
          name: 'Affiliate Program',
          link: 'https://mycryptocheckout.com/affiliates/',
        },
        {
          name: 'IDO Presale Info',
          link: 'https://mycryptocheckout.com/rwd/',
        },
      ],
      images: {
        logo: 'https://icodrops.com/wp-content/uploads/2021/06/MyCryptoCheckout_logo-150x150.jpeg',
        img: '',
        video: 'https://www.youtube.com/embed/nUoJ9ziaAJQ',
      },
    },

    {
      name: 'Coin98 Labs',
      category: 'Platform',
      goal: '$3,750,000',
      interest: 'Not Rated',
      dateActive: '4d left',
      column: 'none',
      date: '2021-08-17T09:35:00',
      important: 'Coin98 Labs will hold a IEO on the 16. Aug. The IEO will happen on Binance.',
      ticker: 'C98',
      tokenType: 'ERC20',
      tokenPrice: '1 C98 = 0.075 USD',
      fundraisingGoal: '50,000,000 TOKEN',
      totalTokens: '1,000,000,000',
      tokenSale: '50%',
      roleOfToken: 'UTILITY',
      links: [
        {
          name: 'IEO Info',
          link: 'https://launchpad.binance.com/en/subscription/C98_BNB',
        },
      ],
      images: {
        logo: 'https://icodrops.com/wp-content/uploads/2021/07/Coin98Labs_logo-150x150.jpeg',
        img: 'https://icodrops.com/wp-content/uploads/2021/07/xxx-1.png',
        video: '',
      },
    },
    {
      name: 'Hi',
      category: 'Blockchain Service',
      goal: 'NOT SET',
      interest: 'Not Rated',
      dateActive: 'TBA',
      column: 'none',
      date: '2021-08-17T15:35:00',
      important: 'Hi will hold a Pre-Sale on the 30. Jul.',
      ticker: 'HI',
      tokenType: 'ERC20',
      tokenPrice: '1 HI = 0.01 USD',
      fundraisingGoal: 'TOKEN',
      totalTokens: '',
      tokenSale: '',
      roleOfToken: 'UTILITY',
      links: [],
      images: {
        logo: 'https://icodrops.com/wp-content/uploads/2021/07/hi_logo-150x150.png',
        img: '',
        video: 'https://www.youtube.com/embed/f5uiqE5e-1s',
      },
    },
    {
      name: 'Altair',
      category: 'Blockchain Service',
      goal: 'NOT SET',
      interest: 'Not Rated',
      dateActive: 'TBA',
      column: 'none',
      date: '2021-08-17T11:35:00',
      important:
        'Altair will hold a crowdloan and also the distribution through the airdrop on the 21. Sep.',
      ticker: 'AIR',
      tokenType: 'ERC20',
      tokenPrice: '1 AIR = 0.53 USD',
      fundraisingGoal: 'TOKEN',
      totalTokens: '505,000,000',
      tokenSale: '',
      roleOfToken: 'UTILITY',
      links: [
        {
          name: 'Crowdloan Info',
          link: 'https://medium.com/altair-network/the-altair-crowdloan-is-now-live-8b77b0bf7739',
        },
      ],
      images: {
        logo: 'https://icodrops.com/wp-content/uploads/2021/07/Altair_logo-1-150x150.jpeg',
        img: 'https://icodrops.com/wp-content/uploads/2021/07/x-5.png',
        video: '',
      },
    },
    {
      name: 'PolkaCipher',
      category: 'Blockchain Service',
      goal: '$2,020,000',
      interest: 'Not Rated',
      dateActive: 'in 16h',
      column: 'none',
      date: '2021-08-26T09:35:00',
      important:
        'PolkaCipher will hold a Initial Dex Offering on the 25. Jul. The IDO will happen on TrustPad. ',
      ticker: 'CPHR',
      tokenType: 'ERC20',
      tokenPrice: '1 CPHR = 0.017 USD',
      fundraisingGoal: '9,000,000 TOKEN',
      totalTokens: '1,000,000,000',
      tokenSale: '18,9%',
      roleOfToken: 'UTILITY',
      links: [
        { name: 'Tokenomics', link: 'https://docsend.com/view/pu35228mckwdxuv7' },
        {
          name: 'IDO Info',
          link: 'https://polkacipher.medium.com/polkacipher-whitelisting-details-for-trustpad-ido-c0dcc67d9868',
        },
      ],
      images: {
        logo: 'https://icodrops.com/wp-content/uploads/2021/07/PolkaCipher_logo-150x150.jpeg',
        img: 'https://icodrops.com/wp-content/uploads/2021/07/x-11.png',
        video: '',
      },
    },
    {
      name: 'Scaleswap',
      category: 'Blockchain Service',
      goal: '$2,500,000',
      interest: 'Not Rated',
      dateActive: 'in 41h',
      column: 'none',
      date: '2021-08-26T09:35:00',
      important: 'Scaleswap will hold a Initial Dex Offering on the 25. Aug.',
      ticker: 'SCA',
      tokenType: 'ERC20',
      tokenPrice: '1 SCA = 0.35 USD',
      fundraisingGoal: '500,000 TOKEN',
      totalTokens: '25,000,000',
      tokenSale: '46,35%',
      roleOfToken: 'UTILITY',
      links: [
        {
          name: 'Strategic Round',
          link: 'https://markets.businessinsider.com/news/stocks/scaleswap-raises-2-5-million-to-build-layer-2-ido-launchpad-1030446861',
        },
        {
          name: 'Token Info',
          link: 'https://medium.com/scaleswap/introducing-the-scaleswap-sca-token-utility-and-benefits-d9eeb84fe44a',
        },
        {
          name: 'IDO Info',
          link: 'https://medium.com/scaleswap/scaleswap-ido-announcement-shooting-together-for-the-moon-3997fa66870a',
        },
      ],
      images: {
        logo: 'https://icodrops.com/wp-content/uploads/2021/05/Scaleswap_logo-150x150.jpeg',
        img: 'https://icodrops.com/wp-content/uploads/2021/05/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA-%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0-2021-05-20-%D0%B2-17.08.02.png',
        video: '',
      },
    },
    {
      name: 'Vent Finance',
      category: 'DeFi',
      goal: '$1,020,000',
      interest: 'Not Rated',
      dateActive: '22 Jul',
      column: 'none',
      date: '2021-07-19T13:35:00',
      important:
        'Vent Finance will hold a Initial Dex Offering on the 10. Sept. The IDO will happen on VentUp.',
      ticker: 'VENT',
      tokenType: 'ERC20',
      tokenPrice: '',
      fundraisingGoal: 'TOKEN',
      totalTokens: '250,000,000',
      tokenSale: '26,81%',
      roleOfToken: 'UTILITY',
      links: [
        {
          name: 'Pre-Seed Funding Round',
          link: 'https://ventfinance.medium.com/ventup-io-raises-100-000-in-pre-seed-funding-to-launch-an-inclusive-cardano-based-ido-launchpad-dccac4765b4b',
        },
        {
          name: 'SHO Info',
          link: 'https://daomaker.com/company/vent-finance',
        },
      ],
      images: {
        logo: 'https://icodrops.com/wp-content/uploads/2021/06/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA-%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0-2021-07-15-%D0%B2-12.24.54-150x150.png',
        img: 'https://icodrops.com/wp-content/uploads/2021/06/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA-%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0-2021-07-15-%D0%B2-12.26.22.png',
        video: '',
      },
    },
    {
      name: 'DeRace',
      category: 'Blockchain Service',
      goal: '1,700,000',
      interest: 'Not Rated',
      dateActive: '26 Jul',
      column: 'none',
      date: '2021-06-19T17:35:00',
      important:
        'DeRace will hold a Strong Holder Offering on the 26. Jul. The SHO will happen on DAO Maker.',
      ticker: 'DERC',
      tokenType: 'ERC20',
      tokenPrice: '1 DERC = 0.05 USD',
      fundraisingGoal: '7,200,000 TOKEN',
      totalTokens: '120,000,000',
      tokenSale: '34%',
      roleOfToken: 'UTILITY',
      links: [
        {
          name: 'Token Metrics',
          link: 'https://www.derace.io/wp-content/uploads/2021/06/DeRace-Tokenmetrics.pdf',
        },
        {
          name: 'Private Round',
          link: 'https://deracenft.medium.com/derace-closes-an-oversubscribed-private-round-raising-1-7m-55d80101c732',
        },
        {
          name: 'SHO info',
          link: 'https://daomaker.com/company/derace',
        },
      ],
      images: {
        logo: 'https://icodrops.com/wp-content/uploads/2021/07/DeRace_logo-150x150.jpeg',
        img: 'https://icodrops.com/wp-content/uploads/2021/07/x-12.png',
        video: '',
      },
    },
    {
      name: 'CryptoArt.Ai',
      category: 'Marketplace',
      goal: '$1,120,000',
      interest: 'Not Rated',
      dateActive: '18 Jul',
      column: 'none',
      date: '2021-07-26T15:35:00',
      important:
        ' CryptoArt.Ai will hold a Initial Dex Offering on the 18. Jul. The IDO will happen on Poolz.',
      ticker: 'CART',
      tokenType: 'ERC20',
      tokenPrice: '9100 CART = 1 ETH',
      fundraisingGoal: '500,000 TOKEN',
      totalTokens: '',
      tokenSale: '',
      roleOfToken: 'UTILITY',
      links: [],
      images: {
        logo: 'https://icodrops.com/wp-content/uploads/2021/06/CryptoArt.Ai_logo-150x150.jpeg',
        img: 'https://icodrops.com/wp-content/uploads/2021/06/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA-%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0-2021-06-16-%D0%B2-14.29.11.png',
        video: '',
      },
    },
    {
      name: 'Glimpse',
      category: 'Marketplace',
      goal: '$1,300,000',
      interest: 'Not Rated',
      dateActive: '16 Jul',
      column: 'none',
      date: '2021-07-26T11:35:00',
      important:
        'Glimpse will hold a Initial Dex Offering on the 16. Jul. The IDO will happen on BSCPad.',
      ticker: 'GLMS',
      tokenType: 'ERC20',
      tokenPrice: '',
      fundraisingGoal: 'TOKEN',
      totalTokens: '',
      tokenSale: '',
      roleOfToken: 'UTILITY',
      links: [
        {
          name: 'Private Round',
          link: 'https://medium.com/glimpsenft/glimpse-raises-over-1-3m-in-private-round-3bea2b38474e',
        },
        {
          name: 'Bounty Program',
          link: 'https://medium.com/glimpsenft/glimpse-bounty-program-requirements-instructions-how-to-participate-f0ac6c79b68e?source=collection_home---6------1-----------------------',
        },
      ],
      images: {
        logo: 'https://icodrops.com/wp-content/uploads/2021/06/Glimpse_logo-150x150.jpeg',
        img: 'https://icodrops.com/wp-content/uploads/2021/06/z.png',
        video: '',
      },
    },
    {
      name: 'Omni',
      category: 'Dapp',
      goal: '$200,000',
      interest: 'Not Rated',
      dateActive: '16 Jul',
      column: 'none',
      date: '2021-08-28T22:35:00',
      important: 'Omni will hold a Initial Dex Offering on the 16. Jul.',
      ticker: 'OMNI',
      tokenType: 'ERC20',
      tokenPrice: '1 OMNI = 0.02 USD',
      fundraisingGoal: 'TOKEN',
      totalTokens: '',
      tokenSale: '18%',
      roleOfToken: 'UTILITY',
      links: [
        {
          name: 'IDO Info',
          link: 'https://medium.com/omni-app/omni-will-have-anti-bot-protection-during-our-pancake-swap-listing-9c729c1f6214',
        },
      ],
      images: {
        logo: 'https://icodrops.com/wp-content/uploads/2021/03/Omni_logo-150x150.jpg',
        img: 'https://icodrops.com/wp-content/uploads/2021/03/Omni_cover.png',
        video: '',
      },
    },
    {
      name: 'YOLOrekt',
      category: 'Blockchain Service',
      goal: '$320,000',
      interest: 'Not Rated',
      dateActive: '16 Jul',
      column: 'none',
      date: '2021-07-26T13:35:00',
      important: 'YOLOrekt will hold a Liquidity Pool on the 13. Jul.',
      ticker: 'YOLO',
      tokenType: 'ERC20',
      tokenPrice: '',
      fundraisingGoal: 'TOKEN',
      totalTokens: '1,000,000,000',
      tokenSale: '',
      roleOfToken: 'UTILITY',
      links: [
        {
          name: 'Liquditi Pool Info',
          link: 'https://medium.com/yolorekt/the-yolorekt-token-issuance-has-arrived-c1f0e9827840',
        },
      ],
      images: {
        logo: 'https://icodrops.com/wp-content/uploads/2021/07/YOLOrekt_logo-150x150.png',
        img: '',
        video: 'https://player.vimeo.com/video/569561395?dnt=1&app_id=122963&h=afd846de35',
      },
    },
  ],
  users: [
    { name: 'Yevhenii', email: 'yevhenii@gmail.com', password: '1234', role: 'admin' },
    { name: 'Roman', email: 'roman@gmail.com', password: '12345', role: 'admin' },
    { name: 'Vladimir', email: 'vova@gmail.com', password: '123456', role: 'user' },
  ],
};

export default data;
